### PR TITLE
Deploy mdbook in guide folder, preserve branch history

### LINKED ISSUE #366: syntax guide seems to be down
When I go to https://projectfluent.org/fluent/guide/, it says page not found.

### PR DESCRIPTION
**Pull request by flodolo**
This builds the book in a `guide` subfolder, and preserves the history of the `gh-pages` branch (in case of issues).

Fixes #366

### CODE REVIEW

**Comment by flodolo** [comment]
It's hard to tell if this is enough to fix the issue 🤔 

On my fork I can see the pages on `/guide`, but is that enough?
https://flodolo.github.io/fluent/guide/

**Review by eemeli — APPROVED** [review]
This looks like it _should_ fix the issue.

**Comment by flodolo** [comment]
Thanks, let's check in a couple of minutes 🤞🏼 

I confess I'm quite confused on how projectfluent.org is set up.

**Comment by flodolo** [comment]
I can see the correct gitbook output in https://projectfluent.org/fluent/guide/ 🥳

**Pull request merged**
